# Site settings
title: Kaiming Cui's Homepage
name: Kaiming Cui
email: Kaiming.Cui@warwick.ac.uk
url: https://cuikaiming.com/
description: "This is Kaiming Cui's Homepage for Astrophysical Research."
keywords: "Astrophysics"
skills: "Ph.D. in Astrophysics"
meta_author: Kaiming Cui

# Google webmaster tools
google_verify: "GXS9e-4rcXIrejIdhP_2UM7IqXD6cchkvy0ti5IPdr4"

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify: "9860267A914DADE8C3767077B8A199BF"

# Contact form:
#Â - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
# contact: none

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 22262c #80B3FF
  primary-rgb: "34, 38, 44" #"24,288,156" #"128,179,255"
  secondary: 362f2c #2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  email: Kaiming.Cui@warwick.ac.uk
  copyright: Kaiming Cui
  location: United Kingdom
  # social: Around the Web
  credits: Credits

Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #   url: http://twitter.com/jekyllrb
  # - title: facebook
  #   url:
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket
  #   url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/ckm3
  - title: envelope
    url: mailto:cuikaiming@sjtu.edu.cn


# Postal address (add as many lines as necessary)
address:
  - line: University of Warwick
  - line: Millburn House, Coventry

# Credits content
credits: 'This homepage is based on Freelance. Freelancer is a free to use, open source Bootstrap theme created by <a style="color:#8383a2; href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
